Sistema_de_controle_Bancario/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  scope(path_names: { new: 'novo', edit: 'editar' }) do
    resources :bank_agencies, path: 'agencias'
  end

  scope(path_names: { new: 'novo', edit: 'editar' }) do
    resources :bank_accounts, path: 'contas'
  end

  scope(path_names: { new: 'registro', edit: 'editar' }) do
    resources :users, except: [:index], path: 'usuarios'
  end

  get 'acesso', to: 'sessions#new'
  post 'acesso', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
end

Sistema_de_controle_Bancario/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Sistema_de_controle_Bancario/app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :bank_agency
  validates :account_number, presence: true, uniqueness: { case_sensitive: false }
  validates :limit, presence: true
end

Sistema_de_controle_Bancario/app/models/bank_agency.rb
class BankAgency < ApplicationRecord
  has_many :bank_accounts, dependent: :restrict_with_error
  has_one_attached :image

  validates :name, presence: true
  validates :number, presence: true, uniqueness: { case_sensitive: false }
  validates :address, presence: true
  validates :image, presence: true
  validate :acceptable_image

  def acceptable_image
    return unless image.attached?

    if image.byte_size > 1.megabyte
      errors.add(:image, 'deve ser de até 1 mb')
    end

    acceptable_types = ['image/jpeg', 'image/png']
    unless acceptable_types.include?(image.content_type)
      errors.add(:image, 'deve ser JPEG ou PNG')
    end
  end
end

Sistema_de_controle_Bancario/app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 5, maximum: 30 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

Sistema_de_controle_Bancario/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  unless ActionController::Base.config.consider_all_requests_local
    rescue_from Exception, with: :server_error
    rescue_from ActiveRecord::RecordNotFound, with: :not_found
  end

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = 'Você deve estar logado para realizar esta ação!'
      redirect_to acesso_path
    end
  end

  private

  def not_found
    render template: '/errors/404', status: 404
  end

  def server_error
    render template: '/errors/500', status: 500
  end

  def set_locale
    I18n.locale = 'pt-BR'
  end
end

Sistema_de_controle_Bancario/app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]
  before_action :require_user

  def index
    @bank_accounts = BankAccount.paginate(page: params[:page], per_page: 5)
  end

  def new
    @bank_account = BankAccount.new
  end

  def create
    @bank_account = BankAccount.new(bank_account_params)

    if @bank_account.save
      flash[:notice] = 'Conta bancária criada com sucesso!'
      redirect_to new_bank_account_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @bank_account.update(bank_account_params)
      flash[:notice] = 'Conta bancária atualizada com sucesso!'
      redirect_to bank_account_path(@bank_account)
    else
      render 'edit'
    end
  end

  def destroy
    @bank_account.destroy
    flash[:notice] = 'Conta bancária removida com sucesso!'
    redirect_to bank_accounts_path
  end

  private

  def set_bank_account
    @bank_account = BankAccount.find(params[:id])
  end

  def bank_account_params
    params.require(:bank_account).permit(:account_number, :limit, :bank_agency_id)
  end
end

Sistema_de_controle_Bancario/app/controllers/bank_agencies_controller.rb
class BankAgenciesController < ApplicationController
  before_action :set_bank_agency, only: [:show, :edit, :update, :destroy]
  before_action :require_user

  def index
    @bank_agencies = BankAgency.paginate(page: params[:page], per_page: 5)
  end

  def new
    @bank_agency = BankAgency.new
  end

  def create
    @bank_agency = BankAgency.new(bank_agency_params)

    if @bank_agency.save
      flash[:notice] = 'Agência bancária criada com sucesso!'
      redirect_to new_bank_agency_path
    else
      render 'new'
    end
  end

  def show
    @bank_accounts = @bank_agency.bank_accounts.paginate(page: params[:page], per_page: 5)
  end

  def edit
  end

  def update
    if @bank_agency.update(bank_agency_params)
      flash[:notice] = 'Agência bancária atualizada com sucesso!'
      redirect_to bank_agency_path(@bank_agency)
    else
      render 'edit'
    end
  end

  def destroy
    if @bank_agency.destroy
      flash[:notice] = 'Agência bancária removida com sucesso!'
    else
      flash[:alert] = "#{@bank_agency.name} não pode ser removida, pois possui contas bancárias!"
    end
    redirect_to bank_agencies_path
  end

  private

  def set_bank_agency
    @bank_agency = BankAgency.find(params[:id])
  end

  def bank_agency_params
    params.require(:bank_agency).permit(:name, :number, :address, :image)
  end
end

Sistema_de_controle_Bancario/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

Sistema_de_controle_Bancario/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Bem-vindo #{user.username}!"
      redirect_to root_path
    else
      flash.now[:alert] = 'Há algo errado com os seus dados de acesso!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Volte sempre!'
    redirect_to root_path
  end
end

Sistema_de_controle_Bancario/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Bem-vindo #{@user.username}!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Usuário atualizado com sucesso!'
      redirect_to root_path
    else 
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:notice] = 'Usuário excluído com sucesso!'
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

Sistema_de_controle_Bancario/app/helpers/application_helper.rb
module ApplicationHelper
end

Sistema_de_controle_Bancario/app/views/bank_accounts/_bank_accounts.html.erb
<div class="container">
  <% obj.each do |bank_account| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <h4 class= "text-success">
              <%= bank_account.account_number %>
            </h4>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to bank_account.bank_agency.name, bank_agency_path(bank_account.bank_agency), class: "text-info" %>
            </h5>

            <p style="font-size: 20px;">
              <span class="card-text text-info">Limite: </span>
              <span class="card-text text-success">
                <%= number_to_currency(bank_account.limit, :unit => "R$ ", :separator => ",", :delimiter => ".") %>
              </span>
            </p>

            <%= link_to "Visualizar", bank_account_path(bank_account), class: "btn btn-outline-success" %>
            <%= link_to "Editar", edit_bank_account_path(bank_account), class: "btn btn-outline-info" %>
            <%= link_to "Remover", bank_account_path(bank_account), class: "btn btn-outline-danger", 
                method: :delete, data: {confirm: "Você tem certeza que deseja remover?"} %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

Sistema_de_controle_Bancario/app/views/bank_accounts/_form.html.erb
<div class="container">
  <%= render 'shared/errors', obj: @bank_account %>

  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @bank_account, class: "shadow p-3 mb-3 formAccount rounded", local: true) do |f| %>

        <div class="form-group row">
          <%= f.label :account_number, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :account_number, class: "form-control shadow rounded", 
              placeholder: "Número da conta" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :limit, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_field :limit, class: "form-control shadow rounded", placeholder: "Limite da conta em reais" %>
          </div>
        </div>

        <div class="form-group  row">
          <%= f.label "Agência", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.select :bank_agency_id, BankAgency.pluck(:number, :id), {:include_blank => 'Selecione uma agência'}, 
                class: 'form-control'
            %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div> 

Sistema_de_controle_Bancario/app/views/bank_accounts/edit.html.erb
<h1 class="text-center mt-4">Atualizar conta</h1>
<%= render 'form' %>

Sistema_de_controle_Bancario/app/views/bank_accounts/index.html.erb
<h1 class="text-center mt-4 mb-4">Contas Bancárias</h1>

<div class="flickr_pagination">
  <%= will_paginate @bank_accounts, :previous_label => 'Anterior', :next_label => 'Próximo',
      :container => false 
  %>
</div>

<%= render 'bank_accounts', obj: @bank_accounts %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @bank_accounts, :previous_label => 'Anterior', :next_label => 'Próximo',
      :container => false 
  %>
</div>

Sistema_de_controle_Bancario/app/views/bank_accounts/new.html.erb
<h1 class="text-center mt-4">Criar uma nova conta</h1>
<%= render 'form' %>

Sistema_de_controle_Bancario/app/views/bank_accounts/show.html.erb
<h2 class="text-center mt-4"><%= @bank_account.account_number %></h2>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <h4>
            <%= link_to @bank_account.bank_agency.name, bank_agency_path(@bank_account.bank_agency), class: "text-success" %>
          </h4>
        </div>
        <div class="card-body">
          <div class="card-text text-info">
            <p style="font-size: 20px;">
              <span class="card-text text-info">Limite: </span>
              <span class="card-text text-success">
                <%= number_to_currency(@bank_account.limit, :unit => "R$ ", :separator => ",", :delimiter => ".") %>
              </span>
            </p>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

Sistema_de_controle_Bancario/app/views/bank_agencies/_bank_agency.html.erb
<div class="container">
  <% obj.each do |bank_agency| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <h4 class= "text-success">
              <%= bank_agency.name %>
            </h4>
          </div>
          <div class="card-body">
            <% if bank_agency.image.attached? %>
              <div class="divImage">
                <%= image_tag bank_agency.image  %>
              </div>
            <% end %>

            <h5 class="card-title text-info"><%= 'Número: ' + bank_agency.number %> </h5>

            <p class="card-text text-info" style="font-size: 20px;"><%= 'Endereço: ' + bank_agency.address %></p>

            <%= link_to "Visualizar", bank_agency_path(bank_agency), class: "btn btn-outline-success" %>
            <%= link_to "Editar", edit_bank_agency_path(bank_agency), class: "btn btn-outline-info" %>
            <%= link_to "Remover", bank_agency_path(bank_agency), class: "btn btn-outline-danger", 
                method: :delete, data: {confirm: "Você tem certeza que deseja remover?"} %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

Sistema_de_controle_Bancario/app/views/bank_agencies/_form.html.erb
<div class="container">
  <%= render 'shared/errors', obj: @bank_agency %>

  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @bank_agency, class: "shadow p-3 mb-3 formAgency rounded", local: true) do |f| %>

        <div class="form-group row">
          <%= f.label :name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Nome da agência" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :number, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :number, class: "form-control shadow rounded", 
              placeholder: "Número da agência" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :address, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_field :address, class: "form-control shadow rounded", placeholder: "Endereço da agência" %>
          </div>
        </div>

        <div class="form-group row" style="justify-content: center">
          <% if @bank_agency.image.attached? && !@bank_agency.errors.any? %>
            <div class="divImage">
              <%= image_tag @bank_agency.image  %>
            </div>
          <% end %>
        </div>

        <div class="form-group row">
          <%= f.label :image, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.file_field :image, class: "form-control shadow rounded"%>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div> 

Sistema_de_controle_Bancario/app/views/bank_agencies/_modal_agency.html.erb
<div class="modal fade" id="modalAgency" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title" style="margin: auto;">Contas</h5>
      </div>
      <div class="modal-body">
          <% obj.each do |bank_account|  %>
           <h4><%= link_to bank_account.account_number, bank_account_path(bank_account), class: "text-success" %></h4>
          <% end %>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

Sistema_de_controle_Bancario/app/views/bank_agencies/edit.html.erb
<h1 class="text-center mt-4">Atualizar agência</h1>
<%= render 'form' %>

Sistema_de_controle_Bancario/app/views/bank_agencies/index.html.erb
<h1 class="text-center mt-4 mb-4">Agências Bancárias</h1>

<div class="flickr_pagination">
  <%= will_paginate @bank_agencies, :previous_label => 'Anterior', :next_label => 'Próximo',
      :container => false 
  %>
</div>

<%= render 'bank_agency', obj: @bank_agencies %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @bank_agencies, :previous_label => 'Anterior', :next_label => 'Próximo',
      :container => false 
  %>
</div>

Sistema_de_controle_Bancario/app/views/bank_agencies/new.html.erb
<h1 class="text-center mt-4">Criar uma nova agência</h1>
<%= render 'form' %>

Sistema_de_controle_Bancario/app/views/bank_agencies/show.html.erb
<h2 class="text-center mt-4"><%= @bank_agency.name %></h2>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
            <h5 class="card-title text-success"><%= 'Número: ' + @bank_agency.number %> </h5>
        </div>
        <div class="card-body">
          <% if @bank_agency.image.attached? %>
            <div class="divImage">
              <%= image_tag @bank_agency.image  %>
            </div>
          <% end %>

          <div class="card-text text-info" style="font-size: 20px;"><%= 'Endereço: ' + @bank_agency.address %></div>

          <button type="button" class="btn btn-primary mt-4" data-toggle="modal" data-target="#modalAgency">
            Visualizar Contas
          </button>

          <%= render 'modal_agency', obj: @bank_accounts %>
        </div>
      </div>
    </div>
  </div>
</div>

Sistema_de_controle_Bancario/app/views/layouts/_footer.html.erb
<footer id="footer" class="py-4 text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Banco Ruby On Rails", root_path, class: "text-white" %>
    </small>
  </div>
</footer>

Sistema_de_controle_Bancario/app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" 
         role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

Sistema_de_controle_Bancario/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to "Banco Ruby On Rails", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if logged_in? %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Agências Bancárias
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Criar nova agência", new_bank_agency_path, class: "dropdown-item" %>
            <%= link_to "Visualizar agências", bank_agencies_path, class: "dropdown-item" %>
          </div>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Contas Bancárias
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Criar nova conta", new_bank_account_path, class: "dropdown-item" %>
            <%= link_to "Visualizar contas", bank_accounts_path, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>

        <li class="nav-item">
          <%= link_to "Entrar", acesso_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Registrar", new_user_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    
    <% if logged_in? %>
      <ul class="navbar-nav" style="margin-right: 100px">
        <li class="nav-item dropdown float-right">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <strong><%= current_user.username %></strong>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Visualizar Perfil", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Sair", sair_path, class: "dropdown-item", method: :delete %>
          </div>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

Sistema_de_controle_Bancario/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Banco Ruby On Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

Sistema_de_controle_Bancario/app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white">
  </div>
  </div>
</div>

Sistema_de_controle_Bancario/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">Os seguintes erros ocorreram:</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

Sistema_de_controle_Bancario/app/views/users/_form.html.erb
<div class="container">
  <%= render 'shared/errors', obj: @user %>

  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @user, class: "shadow p-3 mb-3 formRegisterUser rounded", local: true) do |f| %>
        
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Digite o nome do usuário" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Digite o email do usuário" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Digite a #{msg} do usuário" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

Sistema_de_controle_Bancario/app/views/users/_users.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <h4 class= "text-success"><%= @user.username %></h4>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= @user.email %></h5>
          <%= link_to "Editar Perfil",  edit_user_path(@user), class: "btn btn-outline-info" %>
          <%= link_to "Remover Perfil", user_path(@user), class: "btn btn-outline-danger", method: :delete, 
              data: {confirm: "Você tem certeza que deseja remover?"} %>
        </div>
      </div>
    </div>
  </div>
</div>

Sistema_de_controle_Bancario/app/views/users/edit.html.erb
<h1 class="text-center mt-4">Atualizar Perfil</h1>
<%= render 'form', msg: 'nova senha' %>

Sistema_de_controle_Bancario/app/views/users/new.html.erb
<h1 class="text-center mt-4">Registro</h1>
<%= render 'form', msg: 'senha' %>

Sistema_de_controle_Bancario/app/views/users/show.html.erb
<% if logged_in? %>
    <%= render 'users' %>
<% end %>